### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sawa888** [sawa888/protospace-39431#1]
# URL
https://protospace-39431.onrender.com/

**Comment by motomuun** [comment]
@sawa888 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by sawa888** [comment]
ありがとうございました
